bitfinity-network/bitfinity-evm-sdk

src/evmc-client/src/client.rs, src/iceth-client/src/lib.rs, src/iceth-client/test-canister/src/lib.rs
=> Add get_chain_id method

src/did/src/block.rs
=> Fix base fee calculation when block is less than 50% filled

Cargo.toml, src/did/src/mint_order_exemption.rs
=> EPROD-470 encode MintOrderExemptionData method

Cargo.toml, src/did/src/block.rs
We can remove the ethers-core fork as they have remove the `js` feature from the getrandom crate which was conflicting with our wasm compilation
Link to the PR : https://github.com/gakonst/ethers-rs/pull/2433
=> chore: remove ethers-core fork

src/minter-client/src/lib.rs
https://infinityswap.atlassian.net/browse/EPROD-559
=> [EPROD-559] Minter client endpoints rename

src/evm-canister-client/src/client.rs
Issue ticket link: <https://infinityswap.atlassian.net/jira/software/c/projects/EPROD/boards/16?selectedIssue=EPROD-563>
=> EPROD-563 blockchain update methods and disable evm method

Cargo.toml, src/evm-canister-client/src/client.rs
Issue ticket link: <https://infinityswap.atlassian.net/browse/EPROD-582>
=> EPROD 582 fix logging issue after upgrade in all affected canisters

src/did/src/block.rs, src/eth-signer/src/sign_strategy.rs, src/ethereum-json-rpc-client/Cargo.toml, src/ethereum-json-rpc-client/src/lib.rs, src/evm-block-extractor/src/block_extractor.rs, src/evm-block-extractor/src/database/big_query_db_client.rs, src/evm-block-extractor/src/database/mod.rs, src/evm-block-extractor/src/database/postgres_db_client.rs, src/evm-block-extractor/src/rpc.rs, src/evm-block-extractor/src_resources/db/postgres/migrations/00001_create_schema.sql, src/evm-block-extractor/tests/tests/block_extractor_it.rs, src/evm-block-extractor/tests/tests/database_client_it.rs, src/evm-canister-client/src/client.rs
=> [EPROD-690] Persist `StorableExecutionResult` in the database

src/ethereum-json-rpc-client/src/lib.rs
=> [EPROD-727] Fix null ID for eth_blockNumber

src/ethereum-json-rpc-client/src/lib.rs, src/evm-block-extractor/src/rpc.rs, src/evm-block-extractor/src/task/block_extractor.rs, src/evm-block-extractor/tests/tests/server_it.rs
=> Fix certified data endpoint name

src/evm-canister-client/src/client.rs
=> Disable inspect message evm endpoints

.gitignore, Cargo.toml, src/minter-did/Cargo.toml, src/minter-did/src/id256.rs, src/minter-did/src/lib.rs, src/minter-did/src/runes.rs
For convinience of use I also add implemenation of `From` and `TryFrom` traits for RuneId <--> Id256 conversion, but as the `ordinals` dependency is quite heave, I hide them behind a non-default `runes` feature.
Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-832
=> Add runes id support for id256

Cargo.toml, src/did/src/evm_reset_state.rs, src/ethereum-json-rpc-client/src/lib.rs, src/ethereum-json-rpc-client/tests/reqwest/mod.rs, src/evm-canister-client/src/client.rs, src/minter-client/src/lib.rs
https://infinityswap.atlassian.net/browse/EPROD-852
=> [EPROD-852] Remove bft bridge initialization api + eth_gasPrice method in EthJsonRpcClient

src/evm-canister-client/src/client.rs
=> fix wrong reset endpoint name

Cargo.toml
This PR relies on https://github.com/bitfinity-network/canister-sdk/pull/225 . Please, approve that PR before this one.
=> Update canister-sdk 0.18 -> 0.19

.github/workflows/build-test.yml, scripts/test.sh, src/ethereum-json-rpc-client/tests/reqwest/mod.rs, src/ethereum-json-rpc-client/tests/reqwest/rpc_client.rs
Issue ticket link: <https://infinityswap.atlassian.net/browse/EPROD-956>
=> EPROD-956 unstable reqwest tests

src/ethereum-json-rpc-client/src/http_outcall.rs
This PR fixes available cycles check when performing HTTP outcalls with `HttpOutcallClient`.
Before the fix, the code checked if the initiator of the current update call provided enough cycles to perform the outcall. But this check actually doesn't make sense because we never call the `accept_cycles` method, so even if the cycles are provided, they are not transferred to the canister. This is also not an appropriate place to do so, because the call can be initiated by the canister itself through the scheduler, so it's not up to the client to decide whether the operation must be paid by the caller or by the canister itself.
Instead, we now check if the canister itself has enough cycles to perform the call. If not, we bail early to prevent unnecessary consensus stage on the async call. It …
=> Fix cycles check in http_outcall client

src/did/src/lib.rs, src/did/src/revert_blocks.rs, src/evm-canister-client/src/client.rs
Issue ticket link: [EPROD-1076](https://infinityswap.atlassian.net/browse/EPROD-1076)
[EPROD-1076]: https://infinityswap.atlassian.net/browse/EPROD-1076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add did struct for `revert_to_block` method

Cargo.toml, src/did/src/transaction.rs, src/eth-signer/src/ic_sign.rs, src/eth-signer/src/sign_strategy.rs, src/eth-signer/src/transaction.rs, src/eth-signer/tests/test_canister/src/canister.rs, src/register-evm-agent/src/transaction.rs
https://infinityswap.atlassian.net/browse/EPROD-1099
=> [EPROD-1099] fix signature v

Cargo.toml, src/did/src/state.rs
Indices was unused by the public endpoint and it doesn't make sense to make it public.
Ci is broken due to not up-to-date testnet
=> EPROD-1117 removed Indices

src/did/src/hash.rs
This will allow us to use the hash types as clap arguments using clap validation etc.
=> Add FromStr impl for hash structs

Cargo.toml, src/did/src/hash.rs, src/did/src/integer.rs, src/did/src/transaction.rs
Serialization of H64, H160 and H256 is broken, because the function that deserialize works differently from the one that is serializing the data,
causing for instance, bincode to fail when deserializing a previously serialized H160 with serde.
This is causing bitfusion-sdk to fail to put Operations into the ic-task-scheduler.
I haven't bumped the version since this shouldn't be a breaking change on the evm. If evm serialized the data, it would have not worked so far.
=> EPROD-1155 H160, H256, H64, U64, U256 and Bloom aren't serialized correctly

Cargo.toml, src/did/src/ic.rs, src/did/src/init.rs
https://infinityswap.atlassian.net/browse/EPROD-1197
=> EPROD-1197 added block confirmation strategy in EVM canister

src/evm-canister-client/src/client.rs
=> Add missing methods to evm client
