- Cargo.toml
- src/evmc-client/Cargo.toml
- src/evmc-client/README.md
- src/evmc-client/src/agent.rs
- src/evmc-client/src/agent/identity.rs
- src/evmc-client/src/client.rs
- src/evmc-client/src/error.rs
- src/evmc-client/src/ic_client.rs
- src/evmc-client/src/lib.rs
- src/register-evm-agent/src/register_evm_agent/src/agent/generic_identity.rs
- src/register-evm-agent/src/simple_canister/src/state.rs
> [EPROD-337] EVMC Client

- src/evmc-client/src/client.rs
> [EPROD-337] Fix endpoints and add more endpoints

- README.md
- src/evmc-client/src/client.rs
> Update endpoints and readme

- .github/workflows/build-test.yml
- Cargo.toml
- README.md
> Rebranding bitfinity-network

- Cargo.toml
- src/did/Cargo.toml
- src/did/src/error.rs
> PROD-286 is20 dependencies removed

- Cargo.toml
- src/did/Cargo.toml
- src/did/src/block.rs
> [EPROD-350] Support non-legacy transaction to the block

- Cargo.toml
- src/did/Cargo.toml
- src/did/src/block.rs
Reverts bitfinity-network/bitfinity-evm-sdk#11
> Revert "[EPROD-350] Support non-legacy transaction to the block"

- README.md
- src/did/src/block.rs
- src/did/src/constant.rs
- src/did/src/integer.rs
- src/did/src/lib.rs
- src/register-evm-agent/src/simple_canister/src/state/evm.rs
> EPROD-417 added checked_div and checked_mul to U256

- src/eth-signer/Cargo.toml
- src/eth-signer/src/ic_sign.rs
> EPROD 425 Add serializable attributes

- src/eth-signer/src/ic_sign.rs
> Add more derive traits

- Cargo.toml
- src/did/Cargo.toml
- src/did/src/lib.rs
- src/did/src/sign_strategy.rs
- src/eth-signer/src/ic_sign.rs
> Extract signing strategy to bitfinity-evm-sdk

- README.md
- src/register-evm-agent/src/register_evm_agent/Cargo.toml
- src/register-evm-agent/src/register_evm_agent/README.md
- src/register-evm-agent/src/register_evm_agent/src/cli.rs
- src/register-evm-agent/src/register_evm_agent/src/constant.rs
- src/register-evm-agent/src/register_evm_agent/src/error.rs
- src/register-evm-agent/src/register_evm_agent/src/main.rs
- src/register-evm-agent/src/register_evm_agent/src/reservation.rs
- src/register-evm-agent/src/register_evm_agent/src/transaction.rs
- src/register-evm-agent/src/simple_canister/README.md
- src/register-evm-agent/src/simple_canister/src/state/evm.rs
- src/register-evm-agent/src/simple_canister/src/state/evm/account.rs
> EPROD-424 used evmc client in register evm agent

- src/evm-canister-client/Cargo.toml
- src/evm-canister-client/src/client.rs
> [Eprod-448] clean evm client

- Cargo.toml
- src/register-evm-agent/src/register_evm_agent/Cargo.toml
- src/register-evm-agent/src/register_evm_agent/src/agent.rs
- src/register-evm-agent/src/register_evm_agent/src/agent/generic_identity.rs
- src/register-evm-agent/src/register_evm_agent/src/error.rs
- src/register-evm-agent/src/register_evm_agent/src/reservation.rs
- src/register-evm-agent/src/simple_canister/Cargo.toml
- src/register-evm-agent/src/simple_canister/examples/signature.rs
Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-362
> [EPROD-362] Update depencencies

- src/register-evm-agent/src/register_evm_agent/README.md
- src/register-evm-agent/src/register_evm_agent/src/cli.rs
- src/register-evm-agent/src/register_evm_agent/src/reservation.rs
> Add gas price to the reservation tool

- Cargo.toml
- src/did/Cargo.toml
- src/did/src/lib.rs
- src/did/src/notify.rs
https://infinityswap.atlassian.net/browse/EPROD-475
> [EPROD-475] Notifications

- src/did/src/lib.rs
- src/did/src/notify.rs
> fix spelling

- src/did/src/notify.rs
> Fix panic on Notification input decoding

- Cargo.toml
- src/did/src/lib.rs
- src/did/src/mint_order_exemption.rs
Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-470
> EPROD-470 mint order exemption transaction

- Cargo.toml
- README.md
- src/evm-block-extractor/Cargo.toml
- src/evm-block-extractor/src/blocks_writer.rs
- src/evm-block-extractor/src/main.rs
- src/evm-block-extractor/src/rpc_client.rs
Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-468
> EPROD-468 evm block extractor

- src/did/src/error.rs
> Add bad request error

- src/did/src/transaction.rs
> TransactionBuilder clone

- src/did/src/block.rs
- src/did/src/transaction.rs
> [EPROD-534] Add cumulative gas used field

- src/eth-signer/src/ic_sign.rs
https://infinityswap.atlassian.net/browse/EPROD-521
> [EPROD-521] Comment about signature mallability

- src/did/src/transaction.rs
https://infinityswap.atlassian.net/browse/EPROD-521
> [EPROD-521] Signature malleability check

- src/did/src/fees.rs
- src/did/src/lib.rs
- src/did/src/transaction.rs
> feat: add fee history type and helper functions for transaction

- src/did/src/error.rs
- src/did/src/transaction.rs
> [EPROD-540] Update error

- Cargo.toml
- src/did/Cargo.toml
- src/did/src/bytes.rs
- src/did/src/hash.rs
- src/did/src/integer.rs
- src/register-evm-agent/src/simple_canister/src/state/config.rs
- src/register-evm-agent/src/simple_canister/src/state/evm.rs
> Add conversion for the `alloy-primitives`

- Cargo.toml
> versions update

- Cargo.toml
> Refactor Memory Manager

- Cargo.toml
> IC stable structures can be Send

- scripts/dfx_test.sh
- src/did/tests/transaction_it.rs
- src/eth-signer/test_canister/src/canister.rs
> Non-deterministic signatures test

- src/did/src/error.rs
> EPROD-581 chore: add extra data to error

- Cargo.toml
- src/did/Cargo.toml
- src/did/src/lib.rs
- src/did/src/state.rs
- src/evm-canister-client/src/client.rs
https://infinityswap.atlassian.net/browse/EPROD-564
> [EPROD-564] EVMc state recovery API

- src/did/src/error.rs
- src/signature-verification-canister-client/Cargo.toml
- src/signature-verification-canister-client/src/client.rs
> [EPROD-589] Update Signature Verification Client endpoints

- src/did/src/error.rs
- src/did/src/transaction.rs
- src/eth-signer/src/ic_sign.rs
> Cycles payment for ECDSA signing

- src/ethereum-json-rpc-client/src/lib.rs
- src/ethereum-json-rpc-client/tests/reqwest/mod.rs
Issue ticket link: <https://infinityswap.atlassian.net/browse/EPROD-642>
> [EPROD-642] eth_getLogs in jsonrpc client

- Cargo.toml
- src/did/src/init.rs
- src/did/src/lib.rs
- src/did/src/permission.rs
- src/evm-canister-client/Cargo.toml
- src/evm-canister-client/src/client.rs
> [Eprod-659] Add logs endpoints

- Cargo.toml
> fix canister-sdk version

- Cargo.toml
- src/evm-block-extractor/Cargo.toml
- src/evm-block-extractor/README.md
- src/evm-block-extractor/src/blocks_reader.rs
- src/evm-block-extractor/src/blocks_writer.rs
- src/evm-block-extractor/src/constants.rs
- src/evm-block-extractor/src/main.rs
> evm-block-extractor readme and resume block extraction from latest block in zip file

- Cargo.toml
- src/evm-canister-client/src/client.rs
> Add new methods to EVM client

- src/evm-block-extractor/src/main.rs
> Skip missing blocks or blocks with error

- src/evm-block-extractor/src/bin/extractor.rs
- src/evm-canister-client/src/client.rs
> Add batch requests size endpoints

- src/eth-signer/src/sign_strategy.rs
- src/evm-block-extractor/src/block_extractor.rs
- src/register-evm-agent/src/error.rs
> [EPROD-644] `TransactionSigner` error variants

- Cargo.toml
> upd: upgrade deps

- .github/workflows/build-test.yml
- scripts/build.sh
- scripts/dfx_deploy.sh
- scripts/dfx_test.sh
- scripts/test.sh
> [EPROD-697] Add i686 CI tests

- .github/workflows/block-extractor-scheduler.yml
> fix url without base

- .github/workflows/block-extractor-scheduler.yml
- .github/workflows/build-test.yml
> chore(CI): notify on slack incase the EVM extractor fails

- src/minter-client/src/lib.rs
> [Eprod 701] build data for minter canister

- .github/workflows/block-extractor-scheduler.yml
> Update job not to fail incase matrix fails

- .github/workflows/publish-evm-block-extractor.yml
- docker-compose.yml
- src/evm-block-extractor/src/config.rs
> Add CI for publishing images to GCP

- Cargo.toml
- src/did/Cargo.toml
- src/did/src/lib.rs
- src/did/src/logs.rs
https://infinityswap.atlassian.net/browse/EPROD-711
> [EPROD-711] Logs types in did package

- .github/workflows/build-test.yml
- src/evm-block-extractor/src/block_extractor.rs
- src/evm-block-extractor/src/database/big_query_db_client.rs
- src/evm-block-extractor/src/database/mod.rs
- src/evm-block-extractor/src/database/postgres_db_client.rs
- src/evm-block-extractor/src/rpc.rs
- src/evm-block-extractor/tests/tests/block_extractor_it.rs
- src/evm-block-extractor/tests/tests/database_client_it.rs
- src/evm-block-extractor/tests/tests/server_it.rs
> [Eprod 713] Add chain_id to block extractor

- Cargo.toml
- src/did/src/block.rs
- src/evm-block-extractor/src/database/big_query_db_client.rs
- src/evm-block-extractor/src/database/postgres_db_client.rs
- src/evm-block-extractor/tests/tests/database_client_it.rs
> Fix transactions order in full block

- Cargo.toml
- src/did/src/integer.rs
- src/eth-signer/test_canister/src/main.rs
> Upgrade candid

- src/evm-block-extractor/src/rpc.rs
- src/evm-block-extractor/tests/tests/server_it.rs
> Expand rpc

- Cargo.toml
- src/did/src/transaction.rs
https://infinityswap.atlassian.net/browse/EPROD-724
> [EPROD-724] Additional blockNumber types

- src/ethereum-json-rpc-client/src/lib.rs
- src/ethereum-json-rpc-client/tests/reqwest/mod.rs
> Add eth_getBalance and eth_getTransactionCount methods

- .github/workflows/publish-evm-docker-images.yml
> fix docker deploy

- src/did/src/block.rs
- src/did/src/transaction.rs
- src/evm-canister-client/src/client.rs
> upd: Update mint tokens endpoint; add timestamp to `ExecutionResult`

- src/did/src/mint_order_exemption.rs
- src/did/src/notify.rs
- src/evm-block-extractor/README.md
- src/minter-client/src/lib.rs
Issue ticket link: <https://github.com/bitfinity-network/bitfinity-evm-sdk/compare/main...miles-six:bitfinity-evm-sdk:main>
I have been studying this repository for a long time, and whenever I come across a typo, I fix it. 
I discovered 5 typos in 4 files. Then I merged them together.
The code quality is exceptionally high, so sincerely hope my PR can help make this repository more standardized.
> Update readme and fix other typos

- src/ethereum-json-rpc-client/src/reqwest.rs
> EPROD-771 reqwest client should report error status code

- Cargo.toml
- src/evm-block-extractor/src/config.rs
- src/evm-block-extractor/src/constants.rs
- src/evm-block-extractor/src/lib.rs
> chore: Add devnet prefix to the extractor

- Cargo.toml
- src/evm-canister-client/src/client.rs
> [EPROD-772] Add extra endpoints

- Cargo.toml
- src/minter-did/src/order.rs
- src/minter-did/src/reason.rs
https://infinityswap.atlassian.net/browse/EPROD-818
> [EPROD-818] Approve fields in mint order

- src/ethereum-json-rpc-client/src/lib.rs
> chore: add endpoint to send txn in bytes

- src/did/src/state.rs
> [EPROD-802] Trie revamp

- src/minter-did/src/reason.rs
https://infinityswap.atlassian.net/browse/EPROD-818
> [EPROD-818] Signature to approve minted tokens

- src/minter-did/src/order.rs
- src/minter-did/src/reason.rs
https://infinityswap.atlassian.net/browse/EPROD-728
> [EPROD-728] Fee fields in mint order

- src/minter-did/src/order.rs
> mint order data size hotfix

- src/evm-canister-client/src/client.rs
> Add disable/enable zero gas price tx evm endpoints

- src/evm-canister-client/src/client.rs
> revert zero fee endpoint

- src/evm-canister-client/src/client.rs
> chore: add new processing transaction interval endpoints

- src/minter-did/src/error.rs
- src/minter-did/src/id256.rs
- src/minter-did/src/init.rs
- src/minter-did/src/lib.rs
- src/minter-did/src/runes.rs
https://infinityswap.atlassian.net/browse/EPROD-849
> [EPROD-849] Icrc2 minter without spender

- src/minter-did/src/erc721_mint_order.rs
- src/minter-did/src/lib.rs
> EPROD-682 ERC721 mint order

- src/did/src/evm_reset_state.rs
- src/did/src/ic.rs
- src/did/src/lib.rs
- src/evm-canister-client/src/client.rs
> [EPROD-827] New admin set state endpoints

- Cargo.toml
- src/minter-did/src/reason.rs
> Fee payer in icrc2 burn reason

- Cargo.toml
- src/did/src/ic.rs
- src/evm-block-extractor/tests/evm_block_extractor_it.rs
> Remove storable principal

- Cargo.toml
- src/did/src/ic.rs
- src/minter-did/src/reason.rs
https://infinityswap.atlassian.net/browse/EPROD-908
> [EPROD-908] Operation ID removed from burn reason

- .github/workflows/build-test.yml
- Cargo.toml
- src/did/src/block.rs
- src/did/src/hash.rs
- src/did/src/ic.rs
- src/did/src/integer.rs
- src/did/src/permission.rs
- src/did/src/state.rs
- src/did/src/transaction.rs
- src/eth-signer/src/sign_strategy.rs
- src/evm-canister-client/src/client.rs
- src/minter-did/src/erc721_mint_order.rs
> New unboundedmap

- src/did/src/permission.rs
> [EPROD-913] Add reset evm state permission

- Cargo.toml
- src/evm-canister-client/src/client.rs
- src/minter-did/src/init.rs
https://infinityswap.atlassian.net/browse/EPROD-906
> Fee charge contract address in minter init data

- src/ethereum-json-rpc-client/src/lib.rs
> [EPROD-918] Add new endpoint `eth_maxPriorityPerFeeGas`

- Cargo.toml
- src/minter-client/src/lib.rs
- src/minter-did/src/init.rs
- src/minter-did/src/reason.rs
> Derive serialize for ICRC-2 burn reason

- Cargo.toml
- src/minter-did/src/reason.rs
https://infinityswap.atlassian.net/browse/EPROD-902
> [EPROD-902] Approve after mint without additional signature

- Cargo.toml
- src/minter-did/src/reason.rs
> EPROD-885 explicit erc20 token address for erc20 minting

- Cargo.toml
- src/did/src/error.rs
> Add missing error types

- Cargo.toml
- src/eth-signer/src/ic_sign.rs
- src/eth-signer/src/sign_strategy.rs
- src/eth-signer/src/wallet/private_key.rs
- src/eth-signer/tests/test_canister/src/canister.rs
> fix: Management canister signature bug

- Cargo.toml
- src/minter-did/src/order.rs
> Canister sdk v18

- Cargo.toml
- src/ethereum-json-rpc-client/Cargo.toml
- src/ethereum-json-rpc-client/tests/reqwest/mod.rs
- src/minter-did/Cargo.toml
- src/minter-did/src/order.rs
EDIT: It was meant to be a PR about setting some fields as opt, but it eventually became a pr about fixing the flaky reqwest tests
> EPROD-865 optional fields in mint order

- .github/workflows/build-test.yml
- Cargo.toml
- src/did/src/transaction.rs
- src/eth-signer/src/ic_sign.rs
- src/eth-signer/tests/pocket_ic_tests/ic_sign_test_canister.rs
- src/ethereum-json-rpc-client/src/canister_client.rs
- src/ethereum-json-rpc-client/tests/reqwest/mod.rs
- src/evm-canister-client/src/client.rs
- src/register-evm-agent/src/reservation.rs
> Upgrade to Pocket-ic 4.0.0

- Cargo.toml
- src/did/src/hash.rs
- src/did/src/transaction.rs
- src/evm-canister-client/Cargo.toml
> Remove yanked ic-cdk dependency

- Cargo.toml
> [EPROD-976] update canister-sdk

- src/did/src/transaction.rs
> Fix gas price

- src/did/src/block.rs
- src/did/src/constant.rs
- src/did/src/fees.rs
- src/did/src/transaction.rs
https://infinityswap.atlassian.net/browse/EPROD-1000
> [Eprod-1000] legacy tx type

- src/evm-canister-client/src/client.rs
> Add admin_set_testnet_request_ip_header

- Cargo.toml
- just/test.just
- src/did/Cargo.toml
- src/did/src/alloy_primitives_07.rs
- src/did/src/alloy_primitives_08.rs
- src/did/src/bytes.rs
- src/did/src/hash.rs
- src/did/src/integer.rs
- src/did/src/lib.rs
- src/ethereum-json-rpc-client/src/lib.rs
> Support alloy-primitives 08

- src/evm-canister-client/src/client.rs
https://infinityswap.atlassian.net/browse/EPROD-1081
> [EPROD-1081] Add append_block endpoint

- src/evm-canister-client/src/client.rs
> Add is_evm_disabled endpoint

- src/evm-block-extractor/tests/tests/block_extractor_it.rs
> Fix failing test

- src/did/src/integer.rs
- src/eth-signer/src/transaction.rs
- src/eth-signer/src/wallet/mod.rs
- src/eth-signer/src/wallet/private_key.rs
- src/ethereum-json-rpc-client/src/lib.rs
- src/ethereum-json-rpc-client/tests/reqwest/mod.rs
> Get transaction endpoint

- Cargo.toml
- src/evm-canister-client/src/client.rs
https://infinityswap.atlassian.net/browse/EPROD-1095
> [EPROD-1095] min_gas_price endpoints should accept decimal number

- Cargo.toml
> Upgrade to alloy 0.9

- Cargo.toml
- src/did/src/evm_state.rs
- src/did/src/lib.rs
- src/ethereum-json-rpc-client/src/lib.rs
- src/evm-block-extractor/Cargo.toml
- src/evm-block-extractor/README.md
- src/evm-block-extractor/src/task/block_extractor.rs
- src/evm-block-extractor/tests/tests/block_extractor_it.rs
- src/evm-canister-client/src/client.rs
https://infinityswap.atlassian.net/browse/EPROD-1112
>  [EPROD-1112] New evm staging state

- src/did/src/evm_state.rs
- src/evm-block-extractor/tests/tests/block_extractor_it.rs
> Add staging max_block_number

- src/evm-block-extractor/src/task/block_extractor.rs
…us endpoint
https://infinityswap.atlassian.net/browse/EPROD-1122
> [EPROD-1122] Extractor fallback logic

- src/did/src/revert_blocks.rs
- src/did/src/transaction.rs
This pull request contains changes to improve clarity, correctness and structure.
> fix: typos in documentation files

- src/eth-signer/src/sign_strategy.rs
- src/evm-canister-client/src/client.rs
Issue ticket link: <https://infinityswap.atlassian.net/browse/EPROD-1150>
> [EPROD-1150] Small api fixes

- Cargo.toml
> Bump version to 0.44

- src/ethereum-json-rpc-client/src/lib.rs
- src/ethereum-json-rpc-client/tests/reqwest/mod.rs
Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-1162
> [EPROD-1162] Improved batch request

- Cargo.toml
- src/did/Cargo.toml
- src/eth-signer/Cargo.toml
- src/ethereum-json-rpc-client/Cargo.toml
- src/ethereum-json-rpc-client/src/lib.rs
- src/evm-block-extractor/Cargo.toml
- src/evm-block-extractor/src/task/block_extractor.rs
- src/evm-block-extractor/tests/evm_block_extractor_it.rs
- src/evm-block-extractor/tests/tests/block_extractor_it.rs
- src/evm-block-extractor/tests/tests/database_client_it.rs
- src/evm-block-extractor/tests/tests/server_it.rs
- src/evm-canister-client/Cargo.toml
- src/evm-log-extractor/Cargo.toml
- src/icrc-client/Cargo.toml
- src/signature-verification-canister-client/Cargo.toml
https://infinityswap.atlassian.net/browse/EPROD-1168
> [EPROD-1168] Block extractor backward compatibility

- src/evm-block-extractor/src/task/block_extractor.rs
> extractor fix

- Cargo.toml
- src/did/src/rpc/error.rs
- src/did/src/rpc/response.rs
- src/ethereum-json-rpc-client/Cargo.toml
- src/ethereum-json-rpc-client/src/canister_client.rs
- src/ethereum-json-rpc-client/src/error.rs
- src/ethereum-json-rpc-client/src/http_outcall.rs
- src/ethereum-json-rpc-client/src/lib.rs
- src/ethereum-json-rpc-client/src/reqwest.rs
- src/ethereum-json-rpc-client/tests/reqwest/rpc_client.rs
- src/evm-block-extractor/tests/tests/block_extractor_it.rs
Issue ticket link: <https://infinityswap.atlassian.net/browse/EPROD-1179>
> EPROD-1179 ethereum json rpc client error type£

- Cargo.toml
- src/did/src/transaction.rs
- src/eth-signer/src/ic_sign.rs
- src/eth-signer/src/sign_strategy.rs
- src/ethereum-json-rpc-client/tests/reqwest/mod.rs
> Upgrade to alloy 0.15
